apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: into-guesty-flower-pipeline
description: flower Deployment Pipeline 
serialPipeline:
  stages:
  - targetId: flower

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: flower
description: Staging Environment
gke:
  cluster: projects/weareinto-staging/locations/us-central1/clusters/into-guesty-api-staging-cluster
