steps:

# Fetch Project ID from the environment
- id: 'fetch project id'
  name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "PROJECT_ID is $PROJECT_ID"
    sed -i "s/PROJECT_ID/$PROJECT_ID/g" deployment.yaml
    sed -i "s/PROJECT_ID/$PROJECT_ID/g" clouddeploy.yaml
    sed -i "s/PROJECT_ID/$PROJECT_ID/g" fetch_secrets.py

# Replace HOSTNAME in ingress.yaml based on the environment
- id: 'set environment variables and replace HOSTNAME'
  name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if [[ "$PROJECT_ID" == "weareinto" ]]; then
      echo "Setting environment to production"
      sed -i "s/HOSTNAME/str-flower.weareinto.ai/g" ingress.yaml
    else
      echo "Setting environment to staging"
      sed -i "s/HOSTNAME/str-flower-staging.weareinto.ai/g" ingress.yaml
    fi
    echo "Updated ingress.yaml:"
    cat ingress.yaml

# Replace placeholder in deployment.yaml with actual short SHA
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "SHORT_SHA is $SHORT_SHA"
    sed -i "s/SHORT_SHA/$SHORT_SHA/g" deployment.yaml
    echo "Updated deployment.yaml:"
    cat deployment.yaml

# Replace CLUSTER_NAME in clouddeploy.yaml based on the environment
- id: 'set cluster name'
  name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if [[ "$PROJECT_ID" == "weareinto" ]]; then
      echo "Setting cluster to into-cluster"
      sed -i "s/CLUSTER_NAME/into-cluster/g" clouddeploy.yaml
    else
      echo "Setting cluster to into-guesty-api-staging-cluster"
      sed -i "s/CLUSTER_NAME/into-guesty-api-staging-cluster/g" clouddeploy.yaml
    fi
    echo "Updated clouddeploy.yaml:"
    cat clouddeploy.yaml

# build container
- id: 'build flask image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/into-guesty-flower-staging:$SHORT_SHA', '.']

# Push to GCR
- name: 'gcr.io/cloud-builders/docker'
  id: 'pushing flask to GCR'
  args: ['push', 'gcr.io/$PROJECT_ID/into-guesty-flower-staging:$SHORT_SHA']

# Register Cloud Deploy pipeline
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'registering flask pipeline'
  entrypoint: 'bash'
  args:
  - '-c'
  - gcloud deploy apply --file=clouddeploy.yaml --region=us-central1 --project=$PROJECT_ID

# Create a release
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - >
    gcloud deploy releases create release-$BUILD_ID
    --delivery-pipeline=into-guesty-flower-pipeline
    --region=us-central1
    --images=flask_staging_image=gcr.io/$PROJECT_ID/into-guesty-flower-staging:$SHORT_SHA

substitutions:
  _GCR_REGION: "us-central1"
images:
  - "gcr.io/$PROJECT_ID/into-guesty-flower-staging:$SHORT_SHA" 
